#Impute the missing data using the function described in "imputationApproaches.R"
################################################################################

#import imputation functions
source("./Imputation/imputationApproaches.R")
source("utils.R")


#' @title Impute matrix containing missing values
#'
#' @description This function imputes the dataset containing missing values with Rphylopars, corHMM, 
#' MICE, missForest and KNN according the percentage of phylogenetic information.
#' 
#' @usage generateResults(ImputationApproachesNames, NaNImputed, Data, variance_fractions, save = NULL)
#'
#' @param ImputationApproachesNames names of the imputations methods (character vector)
#' @param NaNImputed object containing all the dataset with missing values
#' @param Data simulated Data object
#' @param variance_fractions numerical vector containing the amount of phylogenetic information to include for 
#' the imputation
#' @param save name of the output
#' @param addHint boolean, TRUE meaning what to impute with imputedData added.
#' @return return a .RData object with the data imputed and all the parameters used for.
#'
generateResults <- function(ImputationApproachesNames, NaNImputed, Data, variance_fractions, save = NULL, addHint = FALSE){
  #save all data generated by replicates
  FinalOutput <- list()
  
  #save error by replicates (MCAR, MAR, MNAR, PhyloNA)
  OutputErrorsDataframes <- list()

  #save imputed data
  OutputImputedData <- list()
  OutputImputedDataNames <- c()
  OutputParameters <- list()
  OutputParametersNames <- c()

  replicate <- NaNImputed$DataNaN

  replicate <- deleteEmptylist(replicate)
  
  #variables to define for imputation
  nbrMI <- 5
  k <- 2
  numFun <- weightedMedian
  catFun <- maxCat

  #mixed and/or only continuous and/or only discrete data
  
  if(addHint){
    variance_fractions <- c(2, variance_fractions)
  }
  
  #Define columns for TimeDataframe
  randomType <- c()
  missingDegree <- c()
  partitionName <- c()
  imputeApproachName <- c() #next loop
  var_fraction <- c() #next lopp
  time <- c() #next loop
  
  for(rdn in 1:length(replicate)){
    
    errorDataframes <- list()
    errorDataframeNames <- c()
    imputedData <- list()
    imputedDataNames <- c()
    parameters <- list()
    parametersNames <- c()

    randomApproaches <- replicate[[rdn]]

    subdatasNames <- str_split(names(randomApproaches), "/", simplify = TRUE)
    
    #define error dataframe, contain error value for each trait containing missing values
    uniqueErrorName <- "error"
    errorSubdata <- NULL
    for (p in (1:length(randomApproaches))){
      partition <- randomApproaches[[p]]

      randomType <- c(randomType, rep(subdatasNames[,1][p], each = ((length(ImputationApproachesNames) - 2) 
                                                                    * length(variance_fractions) + 2))) 
      
      missingDegree <- c(missingDegree, rep(subdatasNames[, ncol(subdatasNames)][p],
                                            each = ((length(ImputationApproachesNames) - 2) 
                                                    * length(variance_fractions) + 2)))
      
      #define column partitionName
      rows <- paste(sort(unique(as.character(str_extract(colnames(partition), "(?<=\\/)\\d+")))), collapse = "/")
      pName <- rep(paste(subdatasNames[,2][p], rows, sep = "/"),
                   each = ((length(ImputationApproachesNames) - 2) 
                           * length(variance_fractions) + 2))
      
      missD <- rep(unique(missingDegree), (length(randomApproaches) / length(unique(missingDegree))))
      
      errorName <- paste(unique(randomType)[rdn], unique(pName), missD[p], sep = "/")
      
      #load true data
      trueData <- Data$FinalData[, names(partition), drop = FALSE]
      
      if(rdn == length(replicate)){
        
        pName <- rep(subdatasNames[,2][p], each = ((length(ImputationApproachesNames) - 2) 
                                                   * length(variance_fractions) + 2))
        #missD <- rep(unique(missingDegree), (length(randomApproaches) / length(unique(missingDegree))))
        errorName <- paste(unique(randomType)[rdn], unique(pName), missD[p], sep = "/")
        
        #trueData <- Data$FinalData[row.names(partition), colnames(partition), drop = FALSE]
        
      }
      partitionName <- c(partitionName, pName)
      if(!is.null(errorSubdata) & errorName != uniqueErrorName){
        errorDataframes <- c(errorDataframes, list(errorSubdata))
      }

      if(errorName != uniqueErrorName){
        
        if(rdn == length(replicate)){
          errorDataframeNames <- c(errorDataframeNames, errorName)
        }
        
        uniqueErrorName <- errorName
        approachesName <- rep(ImputationApproachesNames[-c(1,2)], length(variance_fractions))
        var_frac <- rep(variance_fractions, each = length(ImputationApproachesNames[-c(1,2)]))
        
        if(rdn != length(replicate)){
          errorDataframeNames <- c(errorDataframeNames, uniqueErrorName)
        }
        errorSubdata <- NULL
      }
      
      #imputed Data names
      approachesName <- rep(ImputationApproachesNames[-c(1,2)], length(variance_fractions))
      var_frac <- rep(variance_fractions, each = length(ImputationApproachesNames[-c(1,2)]))
      
      if(rdn != length(replicate)){
        missD <- rep(unique(missingDegree), (length(randomApproaches) / length(unique(missingDegree))))
        errorName <- paste(unique(randomType)[rdn], unique(pName), missD[p], sep = "/")
      }
        
      if(length(grep("I.", names(partition))) == ncol(partition)){
        impName <- paste(errorName, ImputationApproachesNames[1], "Imputed", sep = "/")
        paraName <- paste(errorName, ImputationApproachesNames[1], "Param", sep = "/")
        if(ncol(partition) == 1){
          imputedDataNames <- c(imputedDataNames, impName)
          parametersNames <- c(parametersNames, paraName)
        }
        else{
          imputedDataNames <- c(imputedDataNames, c(impName, paste(errorName, var_frac, 
                                                                   approachesName, "Imputed", sep = "/")))
          parametersNames <- c(parametersNames, c(paraName, paste(errorName, var_frac, 
                                                                   approachesName, "Param", sep = "/")))
        }
      }
      
      if(length(grep("F.", names(partition))) == ncol(partition)){
        impName <- paste(errorName, ImputationApproachesNames[2], "Imputed", sep = "/")
        paraName <- paste(errorName, ImputationApproachesNames[2], "Param", sep = "/")
        if(ncol(partition) == 1){
          imputedDataNames <- c(imputedDataNames, impName)
          parametersNames <- c(parametersNames, paraName)
        }
        else{
          imputedDataNames <- c(imputedDataNames, c(impName, paste(errorName, var_frac, 
                                                                   approachesName, "Imputed", sep = "/")))
          parametersNames <- c(parametersNames, c(paraName, paste(errorName, var_frac, 
                                                                  approachesName, "Param", sep = "/")))
        }
      }
      if(length(grep("F.", names(partition))) != ncol(partition) & 
         length(grep("I.", names(partition))) != ncol(partition)){
        imputedDataNames <- c(imputedDataNames, paste(errorName, approachesName, "Imputed", sep = "/"))
        parametersNames <- c(parametersNames, paste(errorName, approachesName, "Param", sep = "/"))
      }

      imputeA <- NA
      varf <- NA
      t <- NA
      error <- NULL
      
      #only discrete data
      if(length(grep("I.", names(partition))) == ncol(partition)){
        start_time <- Sys.time()
        imputedTrait <- imputeDiscreteTraits(partition, Data)
        end_time <- Sys.time()

        #imputeA <- ImputationApproachesNames[1]
        imputeA <- "corHMM"
        varf <- 1
        if(rdn == length(replicate)){
          error <- imputationError(imputedTrait$imputedData, trueData, partition, 
                                            paste(imputeA, subdatasNames[p, 3], sep = "/"), Data)
        }
        else{
          error <- imputationError(imputedTrait$imputedData, trueData, 
                                   partition, paste(imputeA, subdatasNames[p, 4], sep = "/"), Data)
        }
        t <- end_time - start_time
        imputedData <- c(imputedData, list(imputedTrait$imputedData))
        parameters <- c(parameters, list(imputedTrait$parameters))

      }
      
      imputeApproachName <- c(imputeApproachName, imputeA)
      var_fraction <- c(var_fraction, varf)
      time <- c(time, t)

      imputeA <- NA
      varf <- NA
      t <- NA
      #only continuous data
      if(length(grep("F.", names(partition))) == ncol(partition)){
        start_time <- Sys.time()
        imputedTrait <- imputeContinousTraits(partition, Data)
        end_time <- Sys.time()
        #imputeA <- ImputationApproachesNames[2]
        imputeA <- "Rphylopars"
        varf <- 1
        if(rdn == length(replicate)){
          error <- imputationError(imputedTrait$imputedData, trueData, partition, 
                                   paste(imputeA, subdatasNames[p, 3], 1, sep = "/"), Data)
        }
        else{
          error <- imputationError(imputedTrait$imputedData, trueData, partition, 
                                   paste(imputeA, subdatasNames[p, 4], 1, sep = "/"), Data)
        }

        t <- end_time - start_time
        imputedData <- c(imputedData, list(imputedTrait$imputedData))
        parameters <- c(parameters, list(imputedTrait$parameters))
      }
      
      imputeApproachName <- c(imputeApproachName, imputeA)
      var_fraction <- c(var_fraction, varf)
      time <- c(time, t)
      
      if(!is.null(errorSubdata) & !is.null(error)){
        errorSubdata <- merge(errorSubdata, error, by = "trait")
      }
      
      if(is.null(errorSubdata) & !is.null(error)){
        errorSubdata <- error
      }
      
      hint <- NULL
      
      for(v in 1:length(variance_fractions)){
        
        if(addHint & variance_fractions[v] == 2){
          
          discColums <- grep("I.", names(partition))
          contiColums <- grep("F.", names(partition))
          
          if(length(discColums) != 0 & length(contiColums) != 0 &
             (length(discColums) + length(contiColums)) == ncol(partition)){

            hintDisc <- imputeDiscreteTraits(partition[, discColums, drop = FALSE], Data)$probabilities
            hintConti <- imputeContinousTraits(partition[, contiColums, drop = FALSE], Data)$imputedData
            hint <- cbind(hintConti, hintDisc)
          }
          
          else if(length(discColums) == ncol(partition)){
            hint <- imputeDiscreteTraits(partition[, discColums, drop = FALSE], Data)$probabilities
          }
          
          else{
            hint <- imputedTrait$imputedData
          }

        }
        
        method <- 1
        while(method < ((length(ImputationApproachesNames) - 2) * 2)){

          MixedImputationApproaches <- list("imputeMICE", list(partition, nbrMI, method = "pmm",
                                                               variance_fractions[v], Data, hint),
                                            "imputeMissForest", list(partition, variance_fractions[v],
                                                                     maxiter = 10, ntree = 100,
                                                                     mtry = sqrt(ncol(partition)), Data, hint),
                                            "imputeKNN", list(partition, k, numFun, catFun,
                                                              variance_fractions[v], Data, hint),
                                            "gainR", list(partition, variance_fractions[v], Data, 
                                                          batch_size = round(ncol(partition)*0.2), 
                                                          hint_rate = 0.9, alpha = 100, epochs = 10000, hint))
        
          
          #univariate, missrandomForest and imputeKNN don't work.
          if((MixedImputationApproaches[[method]] == "imputeMICE" |
             MixedImputationApproaches[[method]] == "imputeMissForest" |
             MixedImputationApproaches[[method]] == "imputeKNN") & ncol(partition) == 1){
            method <- method + 2
            time <- c(time, NA)
            next
          }
          
          #print(MixedImputationApproaches[[method + 1]])
          start_time <- Sys.time()
          imputedTrait <- do.call(MixedImputationApproaches[[method]], MixedImputationApproaches[[method + 1]])
          end_time <- Sys.time()
          imputedData <- c(imputedData, list(imputedTrait$imputedData))
          parameters <- c(parameters, list(imputedTrait$parameters))

          
          if(is.null(imputedTrait)){
            time <- c(time, NA)
          }
          
          if(!is.null(imputedTrait)){
            time <- c(time, end_time - start_time)
          }
          
          #change name imputation Approaches
          imputeName <- MixedImputationApproaches[[method]]
          imputeName[str_detect(imputeName, "MICE")] <- "MICE"
          imputeName[str_detect(imputeName, "Miss")] <- "MissForest"
          imputeName[str_detect(imputeName, "KNN")] <- "KNN"
          imputeName[str_detect(imputeName, "gain")] <- "GAIN"
          
          imputeApproachName <- c(imputeApproachName, imputeName)
          var_fraction <- c(var_fraction, variance_fractions[v])
          
          if(rdn == length(replicate)){
            error <- imputationError(imputedTrait$imputedData, trueData, partition, 
                                     paste(imputeName,
                                           subdatasNames[p, 3], variance_fractions[v], sep = "/"), Data)
          }
          
          if(rdn != length(replicate)){
            error <- imputationError(imputedTrait$imputedData, trueData, partition, 
                                     paste(imputeName, 
                                           subdatasNames[p, 4], variance_fractions[v], sep = "/"), Data)
          }
          
          if(!is.null(errorSubdata)){
            errorSubdata <- merge(errorSubdata, error, by = "trait")
          }
          
          if(is.null(errorSubdata)){
          errorSubdata <- error
          }

          method <- method + 2
        }

      }
      
    }
    print("imputation done")
    errorDataframes <- c(errorDataframes, list(errorSubdata))
    OutputErrorsDataframes[[rdn]] <- errorDataframes
    names(OutputErrorsDataframes[[rdn]]) <- errorDataframeNames
    names(OutputErrorsDataframes)[rdn] <- paste("Error", names(replicate)[rdn], sep = "/")
    
    OutputImputedData[[rdn]] <- imputedData
    names(OutputImputedData[[rdn]]) <- imputedDataNames
    names(OutputImputedData)[rdn] <- paste("Imputed", names(replicate)[rdn], sep = "/")
    OutputParameters[[rdn]] <- parameters
    names(OutputParameters[[rdn]]) <- parametersNames
    names(OutputParameters)[rdn] <- paste("Parameters", names(replicate)[rdn], sep = "/")
  }
  
  TimeDataframe <- data.frame(random_Type = randomType, partition = partitionName,
                              missing_Degree = missingDegree, variance_fractions = var_fraction,
                              impute_Approach = imputeApproachName, time = time)
  
  #rows where variance_fracitons not equal to 0
  phyloIndex <- which(var_fraction != 0 & var_fraction != 2)
  
  if(length(phyloIndex) != 0){
    imputeApproachNameToChange <- imputeApproachName[phyloIndex]
    #add "+P"
    imputeApproachNameToChange <- paste0(imputeApproachNameToChange, "+P")
    
    TimeDataframe$impute_Approach[phyloIndex] <- imputeApproachNameToChange
  }
  
  phyloIndex <- which(var_fraction == 2)
  if(length(phyloIndex) != 0){
    imputeApproachNameToChange <- imputeApproachName[phyloIndex]
    #add "+P"
    imputeApproachNameToChange <- paste0(imputeApproachNameToChange, "+PI")
    
    TimeDataframe$impute_Approach[phyloIndex] <- imputeApproachNameToChange
  }
  
  #remove rows with missingData
  TimeDataframe <- TimeDataframe[-which(is.na(TimeDataframe$time)), ]
  
  if(length(replicate) == 3){
    FinalOutput <- list(TimeDataframe = TimeDataframe, 
                        MCAR = list(Error = OutputErrorsDataframes[[1]], Imputed = OutputImputedData[[1]], 
                                    Parameters = OutputParameters[[1]]), 
                        MNAR = list(Error = OutputErrorsDataframes[[2]], Imputed = OutputImputedData[[2]], 
                                    Parameters = OutputParameters[[2]]), 
                        PhyloNA = list(Error = OutputErrorsDataframes[[3]], Imputed = OutputImputedData[[3]], 
                                       Parameters = OutputParameters[[3]]))
  }
  
  else{
    FinalOutput <- list(TimeDataframe = TimeDataframe, 
                        MCAR = list(Error = OutputErrorsDataframes[[1]], Imputed = OutputImputedData[[1]], 
                                    Parameters = OutputParameters[[1]]), 
                        MAR = list(Error = OutputErrorsDataframes[[2]], Imputed = OutputImputedData[[2]], 
                                   Parameters = OutputParameters[[2]]), 
                        MNAR = list(Error = OutputErrorsDataframes[[3]], Imputed = OutputImputedData[[3]], 
                                    Parameters = OutputParameters[[3]]),
                        PhyloNA = list(Error = OutputErrorsDataframes[[4]], Imputed = OutputImputedData[[4]], 
                                       Parameters = OutputParameters[[4]]))
  }
  
  if(!is.null(save)){
    save(FinalOutput, file = paste0(save, ".RData"))
  }
  
  return(FinalOutput)
}