#import imputation functions
source("./Imputation/imputationApproaches.R")
source("utils.R")

#' @title Impute matrix containing missing values
#'
#' @description This function imputes the dataset containing missing values with Rphylopars, corHMM, 
#' MICE, missForest and KNN according the percentage of phylogenetic information.
#' 
#' @usage generateResults(ImputationApproachesNames, NaNImputed, Data, variance_fractions, save = NULL, addHint = FALSE, 
#' trait = NULL, split = NULL)
#'
#' @param ImputationApproachesNames names of the imputations methods (character vector)
#' @param NaNImputed object containing all the dataset with missing values
#' @param Data simulated Data object
#' @param variance_fractions numerical vector containing the amount of phylogenetic information to include for 
#' the imputation
#' @param trait character, trait of interest if NULL returns the error value for all the traits, .
#' @param save name of the output
#' @param addHint boolean, TRUE meaning want to impute with imputedData added.
#' @param split index of columns that we want to keep of the missing data.
#' @return return a .RData object with the data imputed and all the parameters used for.

generateResults <- function(ImputationApproachesNames, NaNImputed, Data, variance_fractions, save = NULL, addHint = FALSE, trait = NULL, split = NULL){
  #save all data generated by replicates
  FinalOutput <- list()
  
  #save error by replicates (MCAR, MAR, MNAR, PhyloNA)
  OutputErrorsDataframes <- list()

  #save imputed data
  OutputImputedData <- list()
  OutputImputedDataNames <- c()
  OutputParameters <- list()
  OutputParametersNames <- c()

  replicate <- NaNImputed$DataNaN

  replicate <- deleteEmptylist(replicate)
  
  #variables to define for imputation
  nbrMI <- 1
  k <- 2
  numFun <- weightedMedian
  catFun <- maxCat

  #mixed and/or only continuous and/or only discrete data
  
  if(addHint){
    variance_fractions <- c(2, variance_fractions)
  }
  
  #Define columns for TimeDataframe
  randomType <- c()
  missingDegree <- c()
  partitionName <- c()
  imputeApproachName <- c() #next loop
  var_fraction <- c() #next lopp
  time <- c() #next loop
  
  for(rdn in 1:length(replicate)){
    errorDataframes <- list()
    errorDataframeNames <- c()
    imputedData <- list()
    imputedDataNames <- c()
    parameters <- list()
    parametersNames <- c()

    randomApproaches <- replicate[[rdn]]

    subdatasNames <- str_split(names(randomApproaches), "/", simplify = TRUE)
    
    #define error dataframe, contain error value for each trait containing missing values
    
    for (p in (1:length(randomApproaches))){
      
      partition <- randomApproaches[[p]]
      
      if(!is.null(split)){
        partition <- partition[ , split, drop = FALSE]
      }
      
      uniqueErrorName <- "error"
      errorSubdata <- NULL
      error <- NULL

      #load true data
      trueData <- Data$FinalData[, names(partition), drop = FALSE]
        
      #Phylogenetic imputation approaches
      ###################################
      
      if(is.null(trait)){
        trait <- "A"
      }  
      
      #discrete data
      if(length(grep("I.", names(partition))) == ncol(partition) | trait %in% names(partition) 
         & "imputeDiscrete" %in% ImputationApproachesNames){
        
        imputeA <- "corHMM"
        
        if(trait %in% names(partition) & length(grep("I.", names(partition))) != ncol(partition)){
          start_time <- Sys.time()
          imputedTrait <- imputeDiscreteTraits(partition[, trait, drop = FALSE], Data)
          end_time <- Sys.time()
          
          error <- imputationError(imputedTrait$imputedData, trueData,
                                   partition, paste(imputeA, subdatasNames[p, 4], sep = "/"), Data)
          
          #keep same size output
          traitNames <- names(partition)[-which(names(partition) == error[1,1])]
          dataError <- data.frame("trait" = traitNames, "error" = NA)
          names(dataError)[2] <- names(error)[2]
          error <- rbind(error, dataError)
          error <- error[order(error$trait), ]
        }
        
        else if(length(grep("I.", names(partition))) == ncol(partition)){
          start_time <- Sys.time()
          imputedTrait <- imputeDiscreteTraits(partition, Data)
          #imputedTrait <- list(imputedData = data.frame(trait = 1:5, y = 1:5), parameters = "Top")
          end_time <- Sys.time()

          error <- imputationError(imputedTrait$imputedData, trueData,
                                   partition, paste(imputeA, subdatasNames[p, 4], sep = "/"), Data)
          
        }
        
        t <- end_time - start_time

        varf <- 1
        impName <- paste(imputeA, subdatasNames[p, 4], "Imputed", sep = "/")
        paraName <- paste(imputeA, subdatasNames[p, 4], "Param", sep = "/")
        
        randomType <- c(randomType, subdatasNames[,1][p])
        partitionName <- c(partitionName, subdatasNames[,2][p])
        missingDegree <- c(missingDegree, subdatasNames[,4][p])
        imputeApproachName <- c(imputeApproachName, imputeA)
        imputedData <- c(imputedData, list(imputedTrait$imputedData))
        parameters <- c(parameters, list(imputedTrait$parameters))
        imputedDataNames <- c(imputedDataNames, impName)
        parametersNames <- c(parametersNames, paraName)
        var_fraction <- c(var_fraction, varf)
        time <- c(time, t)

        if(!is.null(errorSubdata) & !is.null(error)){
          errorSubdata <- merge(errorSubdata, error, by = "trait")
        }
        
        if(is.null(errorSubdata) & !is.null(error)){
          #errorSubdata <- data.frame(matrix()
          errorSubdata <- error
        }
      }
      

      #only continuous data
      if(length(grep("F.", names(partition))) == ncol(partition) & "imputeContinuous" %in% ImputationApproachesNames){
        start_time <- Sys.time()
        imputedTrait <- imputeContinousTraits(partition, Data)
        end_time <- Sys.time()
        #imputeA <- ImputationApproachesNames[2]
        imputeA <- "Rphylopars"

        error <- imputationError(imputedTrait$imputedData, trueData, partition, 
                                paste(imputeA, subdatasNames[p, 4], 1, sep = "/"), Data)
        
        t <- end_time - start_time
        imputedData <- c(imputedData, list(imputedTrait$imputedData))
        parameters <- c(parameters, list(imputedTrait$parameters))
        
        varf <- 1
        impName <- paste(imputeA, subdatasNames[p, 4], "Imputed", sep = "/")
        paraName <- paste(imputeA, subdatasNames[p, 4], "Param", sep = "/")
        
        randomType <- c(randomType, subdatasNames[,1][p])
        partitionName <- c(partitionName, subdatasNames[,2][p])
        missingDegree <- c(missingDegree, subdatasNames[,4][p])
        imputeApproachName <- c(imputeApproachName, imputeA)
        imputedData <- c(imputedData, list(imputedTrait$imputedData))
        parameters <- c(parameters, list(imputedTrait$parameters))
        imputedDataNames <- c(imputedDataNames, impName)
        parametersNames <- c(parametersNames, paraName)
        var_fraction <- c(var_fraction, varf)
        time <- c(time, t)
        
        if(!is.null(errorSubdata) & !is.null(error)){
          errorSubdata <- merge(errorSubdata, error, by = "trait")
        }
        
        else if(is.null(errorSubdata) & !is.null(error)){
          errorSubdata <- error
        }
      }
      
      hint <- NULL
      
      for(v in 1:length(variance_fractions)){
        
        if(addHint & variance_fractions[v] == 2){
          
          discColums <- grep("I.", names(partition))
          contiColums <- grep("F.", names(partition))
          
          # if(length(discColums) != 0 & length(contiColums) != 0 &
          #    (length(discColums) + length(contiColums)) == ncol(partition)){
          if(length(discColums) != 0 & length(contiColums) != 0){

            hintDisc <- imputeDiscreteTraits(partition[, discColums, drop = FALSE], Data)$probabilities
            hintConti <- imputeContinousTraits(partition[, contiColums, drop = FALSE], Data)$imputedData
            hint <- cbind(hintConti, hintDisc)
            
            print("hint added")
          }
          
          else if(length(discColums) == ncol(partition)){
            hint <- imputeDiscreteTraits(partition[, discColums, drop = FALSE], Data)$probabilities
          }
          
          else{
            hint <- imputedTrait$imputedData
          }

        }
        
        MixedImputationApproaches <- list("imputeMICE", list(partition, nbrMI,
                                                             variance_fractions[v], Data, hint),
                                          "imputeMissForest", list(partition, variance_fractions[v],
                                                                   maxiter = 10, ntree = 100,
                                                                   mtry = floor(ncol(partition)/3), Data, hint),
                                          "imputeKNN", list(partition, k, numFun, catFun,
                                                            variance_fractions[v], Data, hint),
                                          "gainR", list(partition, variance_fractions[v], Data, 
                                                        batch_size = round(ncol(partition)*0.2), 
                                                        hint_rate = 0.9, alpha = 100, epochs = 10000, hint))
        
        #to use only the imputation methods in ImputationApproachesNames
        methodsIndex <- which(MixedImputationApproaches %in% ImputationApproachesNames)
        
        for(method in methodsIndex){
          #univariate, missrandomForest and imputeKNN don't work.
          if((MixedImputationApproaches[[method]] == "imputeMICE" |
             MixedImputationApproaches[[method]] == "imputeMissForest" |
             MixedImputationApproaches[[method]] == "imputeKNN") & ncol(partition) == 1 & variance_fractions[v] == 0){
            next
          }
          #print(MixedImputationApproaches[[method + 1]])
          start_time <- Sys.time()
          imputedTrait <- do.call(MixedImputationApproaches[[method]], MixedImputationApproaches[[method + 1]])
          end_time <- Sys.time()

          if(is.null(imputedTrait)){
            time <- c(time, NA)
          }
          
          if(!is.null(imputedTrait)){
            time <- c(time, end_time - start_time)
          }
          #change name imputation Approaches
          imputeName <- MixedImputationApproaches[[method]]
          imputeName[str_detect(imputeName, "MICE")] <- "MICE"
          imputeName[str_detect(imputeName, "Miss")] <- "MissForest"
          imputeName[str_detect(imputeName, "KNN")] <- "KNN"
          imputeName[str_detect(imputeName, "gain")] <- "GAIN"

          impName <- paste(imputeName, subdatasNames[p, 4], variance_fractions[v], "Imputed", sep = "/")
          paraName <- paste(imputeName, subdatasNames[p, 4], variance_fractions[v], "Param", sep = "/")
          
          randomType <- c(randomType, subdatasNames[,1][p])
          imputedDataNames <- c(imputedDataNames, impName)
          parametersNames <- c(parametersNames, paraName)
          
          imputeApproachName <- c(imputeApproachName, imputeName)
          var_fraction <- c(var_fraction, variance_fractions[v])
          partitionName <- c(partitionName, subdatasNames[,2][p])
          missingDegree <- c(missingDegree, subdatasNames[,4][p])
          imputedData <- c(imputedData, list(imputedTrait$imputedData))
          parameters <- c(parameters, list(imputedTrait$parameters))
          
          error <- imputationError(imputedTrait$imputedData, trueData, partition,
                                  paste(imputeName,
                                        subdatasNames[p, 4], variance_fractions[v], sep = "/"), Data)
          

          if(!is.null(errorSubdata)){
            errorSubdata <- merge(errorSubdata, error, by = "trait")
          }
          
          if(is.null(errorSubdata)){
            errorSubdata <- error
          }
        }
      }
      
      errorDataframes <- c(errorDataframes, list(errorSubdata))
      errorDataframeNames <- c(errorDataframeNames, names(randomApproaches[p]))
      
    }
    print("imputation done")
    #errorDataframes <- c(errorDataframes, list(errorSubdata))
    OutputErrorsDataframes[[rdn]] <- errorDataframes
    names(OutputErrorsDataframes[[rdn]]) <- errorDataframeNames
    names(OutputErrorsDataframes)[rdn] <- paste("Error", names(replicate)[rdn], sep = "/")
    OutputImputedData[[rdn]] <- imputedData
    
    names(length(OutputImputedData[[rdn]]))
    names(OutputImputedData[[rdn]]) <- imputedDataNames
    names(OutputImputedData)[rdn] <- paste("Imputed", names(replicate)[rdn], sep = "/")
    OutputParameters[[rdn]] <- parameters
    names(OutputParameters[[rdn]]) <- parametersNames
    names(OutputParameters)[rdn] <- paste("Parameters", names(replicate)[rdn], sep = "/")
  }

  
  TimeDataframe <- data.frame(random_Type = randomType, partition = partitionName,
                              missing_Degree = missingDegree, variance_fractions = var_fraction,
                              impute_Approach = imputeApproachName, time = time)
  
  #rows where variance_fractions not equal to 0
  phyloIndex <- which(var_fraction != 0 & var_fraction != 2)
  
  if(length(phyloIndex) != 0){
    imputeApproachNameToChange <- imputeApproachName[phyloIndex]
    #add "+P"
    imputeApproachNameToChange <- paste0(imputeApproachNameToChange, "+P")
    
    TimeDataframe$impute_Approach[phyloIndex] <- imputeApproachNameToChange
  }
  
  phyloIndex <- which(var_fraction == 2)
  if(length(phyloIndex) != 0){
    imputeApproachNameToChange <- imputeApproachName[phyloIndex]
    #add "+P"
    imputeApproachNameToChange <- paste0(imputeApproachNameToChange, "+PI")
    
    TimeDataframe$impute_Approach[phyloIndex] <- imputeApproachNameToChange
  }

  if(length(replicate) == 3){
    FinalOutput <- list(TimeDataframe = TimeDataframe, 
                        MCAR = list(Error = OutputErrorsDataframes[[1]], Imputed = OutputImputedData[[1]], 
                                    Parameters = OutputParameters[[1]]), 
                        MNAR = list(Error = OutputErrorsDataframes[[2]], Imputed = OutputImputedData[[2]], 
                                    Parameters = OutputParameters[[2]]), 
                        PhyloNA = list(Error = OutputErrorsDataframes[[3]], Imputed = OutputImputedData[[3]], 
                                       Parameters = OutputParameters[[3]]))
  }
  
  else{
    FinalOutput <- list(TimeDataframe = TimeDataframe, 
                        MCAR = list(Error = OutputErrorsDataframes[[1]], Imputed = OutputImputedData[[1]], 
                                    Parameters = OutputParameters[[1]]), 
                        MAR = list(Error = OutputErrorsDataframes[[2]], Imputed = OutputImputedData[[2]], 
                                   Parameters = OutputParameters[[2]]), 
                        MNAR = list(Error = OutputErrorsDataframes[[3]], Imputed = OutputImputedData[[3]], 
                                    Parameters = OutputParameters[[3]]),
                        PhyloNA = list(Error = OutputErrorsDataframes[[4]], Imputed = OutputImputedData[[4]], 
                                       Parameters = OutputParameters[[4]]))
  }
  
  if(!is.null(save)){
    save(FinalOutput, file = paste0(save, ".RData"))
  }
  
  return(FinalOutput)
}

